apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: changeme
  labels:
    app: payment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
      labels:
        app: payment-app
    spec:
      containers:
        - name: payments
          image: image-registry.openshift-image-registry.svc:5000/pre-production/payment-application@sha256:672e470ad66b43baa5a66b597927e498b62a6cb836759d1418cf6402c2047b7a
          ports:
            - containerPort: 8080
