apiVersion: batch/v1
kind: Job
metadata:
  name: payment-app-load-simulator
  namespace: cp4i
spec:
  template:
    spec:
      containers:
        - name: payment-app-load-simulator
          image: quay.io/marwan_attar_ibm/payment-app-load-simulator
      restartPolicy: Never
  backoffLimit: 1

