kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: payment-application-build-config
  namespace: cp4i
spec:
  source:
    type: Git
    git:
      uri: 'git@github.com:Mattar555/cicd-java-app-demo.git'
    sourceSecret:
      name: git-ssh-key
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'payment-application:prod'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  postCommit: {}
  runPolicy: Serial
